import PDFDocument from '../common/pdfkit';
import { PassThrough } from 'stream';

export type SalesOfferPdfData = {
  number: string;
  leadRef: string;
  buyerName: string;
  buyerPhone: string;
  buyerEmail: string | null;
  listingLabel: string | null;
  offerPrice: number;
  depositRequired: number | null;
  validityUntil: Date | null;
  paymentTerms: string | null;
  conditions: string | null;
  preparedBy: string | null;
  buyerResponse: string;
  counterPrice: number | null;
  issuedAt: Date;
};

export function buildSalesOfferPdf(data: SalesOfferPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];

    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);

    doc.pipe(stream);

    const money = (n: number) =>
      `NGN ${n.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;

    doc.fontSize(18).fillColor('#1a2744').text('Sales Offer / Quotation', { align: 'center' });
    doc.fontSize(10).fillColor('#666').text('Triple A Realty / A. A Laucarie Consulting', {
      align: 'center',
    });
    doc.moveDown();
    doc.fontSize(10).fillColor('#333');
    doc.text(`Offer No: ${data.number}`);
    doc.text(`Date: ${data.issuedAt.toLocaleDateString('en-NG')}`);
    doc.text(`Lead: ${data.leadRef}`);
    doc.text(`Buyer: ${data.buyerName}`);
    doc.text(`Phone: ${data.buyerPhone}`);
    if (data.buyerEmail) doc.text(`Email: ${data.buyerEmail}`);
    if (data.listingLabel) doc.text(`Listing: ${data.listingLabel}`);
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('Offer terms', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#333');
    doc.text(`Offer price: ${money(data.offerPrice)}`);
    if (data.depositRequired != null) {
      doc.text(`Deposit required: ${money(data.depositRequired)}`);
    }
    if (data.validityUntil) {
      doc.text(`Valid until: ${data.validityUntil.toLocaleDateString('en-NG')}`);
    }
    if (data.paymentTerms) doc.text(`Payment terms: ${data.paymentTerms}`);
    if (data.preparedBy) doc.text(`Prepared by: ${data.preparedBy}`);
    doc.text(`Buyer response: ${data.buyerResponse}`);
    if (data.counterPrice != null) {
      doc.text(`Counter price: ${money(data.counterPrice)}`);
    }

    if (data.conditions) {
      doc.moveDown();
      doc.fontSize(12).fillColor('#1a2744').text('Conditions', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#333').text(data.conditions);
    }

    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor('#666')
      .text(
        'Accepted SOF is required before Reserved stage and lead conversion.',
        { align: 'left' },
      );
    doc.moveDown();
    doc.text('Generated by Propa3', { align: 'center' });

    doc.end();
  });
}
