import PDFDocument from '../common/pdfkit';
import { PassThrough } from 'stream';

export type CloseoutPdfData = {
  number: string;
  projectName: string;
  projectLocation: string | null;
  developerName: string;
  clientName: string;
  durationStart: Date | null;
  durationEnd: Date | null;
  executiveSummary: string;
  accomplishments: { zone: string; items: string[] }[];
  openItems: string | null;
  overBudget: boolean;
  onSchedule: boolean;
  preparedBy: string | null;
  status: string;
  issuedAt: Date | null;
  clientAcknowledgedAt: Date | null;
  clientAcknowledgedBy: string | null;
  createdAt: Date;
};

export function buildCloseoutPdf(data: CloseoutPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];
    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
    doc.pipe(stream);

    const d = (v: Date | null) => (v ? v.toLocaleDateString('en-NG') : '—');

    doc.fontSize(18).fillColor('#1a2744').text('Project Closeout Report', { align: 'center' });
    doc.fontSize(10).fillColor('#666').text('Triple A Realty / A. A Laucarie Consulting', {
      align: 'center',
    });
    doc.moveDown();
    doc.fontSize(10).fillColor('#333');
    doc.text(`Report No: ${data.number}`);
    doc.text(`Status: ${data.status}`);
    doc.text(`Date: ${d(data.issuedAt ?? data.createdAt)}`);
    doc.text(`Project: ${data.projectName}`);
    if (data.projectLocation) doc.text(`Location: ${data.projectLocation}`);
    doc.text(`Developer: ${data.developerName}`);
    doc.text(`Client: ${data.clientName}`);
    doc.text(`Duration: ${d(data.durationStart)} – ${d(data.durationEnd)}`);
    doc.text(
      `Schedule/budget: ${data.onSchedule ? 'On schedule' : 'Behind schedule'} · ${
        data.overBudget ? 'Over budget' : 'Within budget'
      }`,
    );
    if (data.preparedBy) doc.text(`Prepared by: ${data.preparedBy}`);
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('Executive summary', { underline: true });
    doc.moveDown(0.4);
    doc.fontSize(10).fillColor('#333').text(data.executiveSummary);
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('Key accomplishments / features', {
      underline: true,
    });
    doc.moveDown(0.4);
    for (const zone of data.accomplishments) {
      doc.fontSize(11).fillColor('#1a2744').text(zone.zone);
      doc.fontSize(10).fillColor('#333');
      for (const item of zone.items) {
        doc.text(`  • ${item}`);
      }
      doc.moveDown(0.4);
    }

    if (data.openItems) {
      doc.fontSize(12).fillColor('#1a2744').text('Open items', { underline: true });
      doc.moveDown(0.4);
      doc.fontSize(10).fillColor('#333').text(data.openItems);
      doc.moveDown();
    }

    if (data.clientAcknowledgedAt) {
      doc
        .fontSize(10)
        .fillColor('#333')
        .text(
          `Client acknowledgment: ${data.clientAcknowledgedBy || 'Client'} on ${d(
            data.clientAcknowledgedAt,
          )}`,
        );
    }

    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor('#666')
      .text(
        'Closure is not merely construction complete — post-completion M&E and satisfaction items remain traceable (Doc 7).',
      );
    doc.moveDown();
    doc.text('Generated by Propa3', { align: 'center' });
    doc.end();
  });
}
