import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

export type AllocationLetterData = {
  date: Date;
  clientName: string;
  clientAddress: string;
  plotType: string;
  estateName: string;
  area: string;
  plotNumber: string;
  propertyType: string;
  sqm: string;
  phase: string;
  contractRef: string;
  pmName: string;
  pmPhone: string;
};

export function buildAllocationLetterPdf(data: AllocationLetterData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];

    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);

    doc.pipe(stream);

    doc.fontSize(12).fillColor('#1a2744').text('TRIPLE A REALTY PROJECTS LTD', { align: 'center' });
    doc.fontSize(10).text('Suite D15B, Platinum Mega Plaza, Jahi, Abuja', { align: 'center' });
    doc.text('RC No. 8168740', { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(10).fillColor('#333');
    doc.text(`Date: ${data.date.toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' })}`);
    doc.moveDown();
    doc.text(data.clientName);
    doc.text(data.clientAddress);
    doc.moveDown();
    doc.text('Dear Client,');
    doc.moveDown();
    doc.font('Helvetica-Bold').text(
      `RE: ALLOCATION OF ${data.plotType.toUpperCase()} — ${data.estateName.toUpperCase()}, ${data.area.toUpperCase()}, ABUJA`,
    );
    doc.font('Helvetica');
    doc.moveDown();
    doc.text(
      'We refer to your reservation and payment towards the acquisition of property at the above-named estate developed by Triple A Realty Projects Ltd.',
    );
    doc.moveDown();
    doc.text(
      `Pursuant to your application and subject to the terms of the Sale Agreement (reference ${data.contractRef}), we hereby ALLOCATE to you:`,
    );
    doc.moveDown();
    doc.text(`    Estate Name    : ${data.estateName}`);
    doc.text(`    Plot/Unit No.  : ${data.plotNumber}`);
    doc.text(`    Property Type  : ${data.propertyType}`);
    doc.text(`    Land Area      : ${data.sqm} sqm (approx.)`);
    doc.text(`    Block/Phase    : ${data.phase}`);
    doc.moveDown();
    doc.font('Helvetica-Bold').text('CONDITIONS OF ALLOCATION');
    doc.font('Helvetica');
    doc.moveDown(0.5);
    const conditions = [
      'This allocation is subject to the full terms of the Sale Agreement and payment schedule attached hereto.',
      'Title documentation (Survey Plan, Allocation Letter, Deed of Assignment as applicable) shall be processed upon completion of agreed payments.',
      "Construction shall proceed in accordance with Triple A's Agile milestone framework: Foundation → Shell → Finishing, with progress reports provided via the client portal.",
      'This allocation does not constitute a Certificate of Occupancy. C of O processing is subject to FCTA/FCDA requirements and separate arrangements.',
      'Transfer of allocation to a third party requires written consent of Triple A Realty Projects Ltd and payment of applicable fees.',
    ];
    conditions.forEach((c, i) => doc.text(`${i + 1}. ${c}`, { align: 'justify' }));
    doc.moveDown();
    doc.text(
      `Please contact your assigned Project Manager, ${data.pmName}, at ${data.pmPhone} for construction updates and payment enquiries.`,
    );
    doc.moveDown(2);
    doc.text('Yours faithfully,');
    doc.moveDown(3);
    doc.text('_________________________');
    doc.text('Abraham Ahmed');
    doc.text('Founder & CEO');
    doc.text('TRIPLE A REALTY PROJECTS LTD');
    doc.moveDown();
    doc.fontSize(8).fillColor('#666').text('Generated by Propa3 · Draft — requires legal review', {
      align: 'center',
    });

    doc.end();
  });
}
