import PDFDocument from '../common/pdfkit';
import { PassThrough } from 'stream';

export type DepositSettlementPdfData = {
  number: string;
  tenantName: string;
  propertyLabel: string;
  cautionHeld: number;
  totalDeductions: number;
  refundAmount: number;
  shortfallAmount: number;
  status: string;
  moveInNumber: string;
  moveOutNumber: string;
  lines: {
    section: string;
    item: string;
    moveInDefects: string;
    moveOutDefects: string;
    cost: number;
    wearAndTear: boolean;
    chargeable: boolean;
  }[];
  refundPaidAt: Date | null;
  refundReference: string | null;
  shortfallInvoiceNumber: string | null;
  issuedAt: Date;
};

export function buildDepositSettlementPdf(data: DepositSettlementPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];
    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
    doc.pipe(stream);

    const money = (n: number) =>
      `₦${n.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;

    doc.fontSize(18).fillColor('#1a2744').text('Deposit Settlement Statement', {
      align: 'center',
    });
    doc.fontSize(10).fillColor('#666').text('G.14 Move-out · Caution closeout', {
      align: 'center',
    });
    doc.moveDown();
    doc.fontSize(10).fillColor('#333');
    doc.text(`Settlement No: ${data.number}`);
    doc.text(`Status: ${data.status}`);
    doc.text(`Date: ${data.issuedAt.toLocaleDateString('en-NG')}`);
    doc.text(`Tenant: ${data.tenantName}`);
    doc.text(`Property: ${data.propertyLabel}`);
    doc.text(`Move-in: ${data.moveInNumber} · Move-out: ${data.moveOutNumber}`);
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('Summary', { underline: true });
    doc.moveDown(0.4);
    doc.fontSize(10).fillColor('#333');
    doc.text(`Caution held: ${money(data.cautionHeld)}`);
    doc.text(`Total deductions: ${money(data.totalDeductions)}`);
    doc.text(`Refund to tenant: ${money(data.refundAmount)}`);
    doc.text(`Shortfall (tenant owes): ${money(data.shortfallAmount)}`);
    if (data.refundPaidAt) {
      doc.text(
        `Refund paid: ${data.refundPaidAt.toLocaleDateString('en-NG')}${
          data.refundReference ? ` · Ref ${data.refundReference}` : ''
        }`,
      );
    }
    if (data.shortfallInvoiceNumber) {
      doc.text(`Shortfall invoice: ${data.shortfallInvoiceNumber}`);
    }

    doc.moveDown();
    doc.fontSize(12).fillColor('#1a2744').text('Chargeable / wear lines', {
      underline: true,
    });
    doc.moveDown(0.4);
    doc.fontSize(9).fillColor('#333');

    const chargeable = data.lines.filter((l) => l.chargeable || l.wearAndTear || l.cost > 0);
    if (!chargeable.length) {
      doc.text('No deterioration lines — full caution refund eligible.');
    } else {
      for (const l of chargeable.slice(0, 40)) {
        const tag = l.wearAndTear ? 'WEAR' : l.chargeable ? 'CHARGE' : '—';
        doc.text(
          `[${tag}] ${l.section} · ${l.item} · in:${l.moveInDefects || '—'} out:${l.moveOutDefects || '—'} · ${money(l.cost)}`,
        );
      }
      if (chargeable.length > 40) {
        doc.text(`… and ${chargeable.length - 40} more lines`);
      }
    }

    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor('#666')
      .text(
        'Natural wear and tear is not charged. Tenant-caused damage is deducted from caution; shortfall is invoiced (G.14).',
        { align: 'left' },
      );
    doc.moveDown();
    doc.text('Generated by Propa3', { align: 'center' });
    doc.end();
  });
}
