import PDFDocument from '../common/pdfkit';
import { PassThrough } from 'stream';

function list(doc: InstanceType<typeof import('../common/pdfkit').default>, title: string, items: string[]) {
  doc.fontSize(12).fillColor('#1a2744').text(title, { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#333');
  if (!items.length) {
    doc.text('—');
  } else {
    for (const i of items) doc.text(`• ${i}`);
  }
  doc.moveDown(0.6);
}

export function buildCharterPdf(data: {
  number: string;
  title: string;
  projectName: string;
  executiveSummary: string;
  goals: string[];
  deliverables: string[];
  businessCase: string | null;
  benefits: string | null;
  costs: string | null;
  budgetRange: string | null;
  timeline: string | null;
  risks: string[];
  scopeIn: string[];
  scopeOut: string[];
  team: string[];
  successCriteria: string[];
  status: string;
  companySignedBy: string | null;
  companySignedAt: Date | null;
  clientSignedBy: string | null;
  clientSignedAt: Date | null;
  preparedBy: string | null;
  createdAt: Date;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];
    stream.on('data', (c: Buffer) => chunks.push(c));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
    doc.pipe(stream);

    const d = (v: Date | null) => (v ? v.toLocaleDateString('en-NG') : '—');

    doc.fontSize(18).fillColor('#1a2744').text('Project Charter', { align: 'center' });
    doc.fontSize(10).fillColor('#666').text('Triple A Realty / A. A Laucarie Consulting', {
      align: 'center',
    });
    doc.moveDown();
    doc.fontSize(10).fillColor('#333');
    doc.text(`Charter No: ${data.number}`);
    doc.text(`Status: ${data.status}`);
    doc.text(`Project: ${data.projectName}`);
    doc.text(`Title: ${data.title}`);
    if (data.preparedBy) doc.text(`Prepared by: ${data.preparedBy}`);
    doc.text(`Date: ${d(data.createdAt)}`);
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('Executive summary', { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#333').text(data.executiveSummary);
    doc.moveDown();

    list(doc, 'Project goals (SMART)', data.goals);
    list(doc, 'Deliverables', data.deliverables);
    if (data.businessCase) {
      doc.fontSize(12).fillColor('#1a2744').text('Business case', { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor('#333').text(data.businessCase);
      doc.moveDown();
    }
    if (data.benefits) doc.fontSize(10).fillColor('#333').text(`Benefits: ${data.benefits}`);
    if (data.costs) doc.text(`Costs: ${data.costs}`);
    if (data.budgetRange) doc.text(`Budget range: ${data.budgetRange}`);
    if (data.timeline) doc.text(`Timeline: ${data.timeline}`);
    doc.moveDown();
    list(doc, 'Risks & constraints', data.risks);
    list(doc, 'In scope', data.scopeIn);
    list(doc, 'Out of scope', data.scopeOut);
    list(doc, 'Project team / stakeholders', data.team);
    list(doc, 'Measuring success', data.successCriteria);

    doc.fontSize(12).fillColor('#1a2744').text('Signatures', { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#333');
    doc.text(
      `Company: ${data.companySignedBy || '—'} · ${d(data.companySignedAt)}`,
    );
    doc.text(`Client: ${data.clientSignedBy || '—'} · ${d(data.clientSignedAt)}`);
    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor('#666')
      .text('Both signatures required before Planning kick-off may be published (US-INIT-12).');
    doc.moveDown();
    doc.text('Generated by Propa3', { align: 'center' });
    doc.end();
  });
}

export function buildKickoffPdf(data: {
  number: string;
  projectName: string;
  meetingAt: Date;
  location: string | null;
  projectManagerName: string | null;
  preparedBy: string | null;
  attendees: { name: string; role?: string; email?: string; phone?: string }[];
  agenda: { item: string; notes?: string; remark?: string }[];
  actions: { action: string; actionedBy?: string; dueDate?: string }[];
  status: string;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];
    stream.on('data', (c: Buffer) => chunks.push(c));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
    doc.pipe(stream);

    doc.fontSize(18).fillColor('#1a2744').text('Project Kick-Off Meeting', {
      align: 'center',
    });
    doc.fontSize(10).fillColor('#666').text('Minutes', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#333');
    doc.text(`Minutes No: ${data.number}`);
    doc.text(`Status: ${data.status}`);
    doc.text(`Project: ${data.projectName}`);
    doc.text(`Meeting: ${data.meetingAt.toLocaleString('en-NG')}`);
    if (data.location) doc.text(`Location: ${data.location}`);
    if (data.projectManagerName) doc.text(`Project manager: ${data.projectManagerName}`);
    if (data.preparedBy) doc.text(`Minutes prepared by: ${data.preparedBy}`);
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('1. Attendees', { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#333');
    if (!data.attendees.length) doc.text('—');
    else {
      for (const a of data.attendees) {
        doc.text(
          `• ${a.name}${a.role ? ` · ${a.role}` : ''}${a.email ? ` · ${a.email}` : ''}${
            a.phone ? ` · ${a.phone}` : ''
          }`,
        );
      }
    }
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('2. Agenda', { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#333');
    for (const a of data.agenda) {
      doc.text(`• ${a.item}`);
      if (a.notes) doc.text(`    Notes: ${a.notes}`);
      if (a.remark) doc.text(`    Remark: ${a.remark}`);
    }
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('3. Action items', { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#333');
    if (!data.actions.length) doc.text('—');
    else {
      for (const a of data.actions) {
        doc.text(
          `• ${a.action}${a.actionedBy ? ` — ${a.actionedBy}` : ''}${
            a.dueDate ? ` (due ${a.dueDate})` : ''
          }`,
        );
      }
    }
    doc.moveDown(2);
    doc.text('Generated by Propa3', { align: 'center' });
    doc.end();
  });
}
