import PDFDocument from '../common/pdfkit';
import { PassThrough } from 'stream';

export type RemittancePdfData = {
  number: string;
  propertyName: string;
  propertyAddress: string;
  landlordName: string;
  periodStart: Date;
  periodEnd: Date;
  grossRent: number;
  otherReceipts: number;
  expensesTotal: number;
  netAmount: number;
  expenseNotes: string | null;
  bankAccount: string | null;
  transferRef: string | null;
  paidAt: Date | null;
  status: string;
  issuedAt: Date;
};

export function buildRemittancePdf(data: RemittancePdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];

    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);

    doc.pipe(stream);

    const money = (n: number) =>
      `NGN ${n.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;
    const d = (v: Date) => v.toLocaleDateString('en-NG');

    doc.fontSize(18).fillColor('#1a2744').text('Landlord Remittance Advice', { align: 'center' });
    doc.fontSize(10).fillColor('#666').text('Triple A Realty / A. A Laucarie Consulting', {
      align: 'center',
    });
    doc.moveDown();
    doc.fontSize(10).fillColor('#333');
    doc.text(`Remittance No: ${data.number}`);
    doc.text(`Status: ${data.status}`);
    doc.text(`Prepared: ${d(data.issuedAt)}`);
    doc.text(`Period: ${d(data.periodStart)} to ${d(data.periodEnd)}`);
    doc.text(`Property: ${data.propertyName}`);
    doc.text(`Address: ${data.propertyAddress}`);
    doc.text(`Landlord: ${data.landlordName}`);
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('Computation', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#333');
    doc.text(`Gross rent collected: ${money(data.grossRent)}`);
    doc.text(`Other receipts: ${money(data.otherReceipts)}`);
    doc.text(`Gross total: ${money(data.grossRent + data.otherReceipts)}`);
    doc.text(`Less: approved expenses: ${money(data.expensesTotal)}`);
    doc.fontSize(11).fillColor('#1a2744').text(`Net remittance: ${money(data.netAmount)}`);

    if (data.expenseNotes) {
      doc.moveDown();
      doc.fontSize(12).fillColor('#1a2744').text('Expense notes', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#333').text(data.expenseNotes);
    }

    doc.moveDown();
    doc.fontSize(12).fillColor('#1a2744').text('Payment', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#333');
    doc.text(`Bank / account: ${data.bankAccount || '—'}`);
    doc.text(`Transfer ref: ${data.transferRef || '—'}`);
    doc.text(`Remittance date: ${data.paidAt ? d(data.paidAt) : '—'}`);

    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor('#666')
      .text(
        'Net = Gross collected + other receipts − approved expenses (BRD G.9–G.10). Exact client accounting rules remain configurable until confirmed.',
      );
    doc.moveDown();
    doc.text('Generated by Propa3', { align: 'center' });

    doc.end();
  });
}
