import PDFDocument from '../common/pdfkit';
import { PassThrough } from 'stream';

type ReceiptData = {
  receiptNumber: string;
  invoiceNumber: string;
  clientName: string;
  amount: number;
  verifiedAt: Date;
  settlementEntity: {
    name: string;
    bankName: string;
    accountName: string;
    accountNumber: string;
  };
};

export function buildReceiptPdf(data: ReceiptData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];

    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);

    doc.pipe(stream);

    doc.fontSize(18).fillColor('#1a2744').text('Propa3 — Payment Receipt', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#333');
    doc.text(`Receipt No: ${data.receiptNumber}`);
    doc.text(`Invoice No: ${data.invoiceNumber}`);
    doc.text(`Date: ${data.verifiedAt.toLocaleDateString('en-NG')}`);
    doc.moveDown();
    doc.text(`Received from: ${data.clientName}`);
    doc.text(`Amount: ₦${data.amount.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`);
    doc.moveDown();
    doc.text('Settlement details:', { underline: true });
    doc.text(`${data.settlementEntity.name}`);
    doc.text(`${data.settlementEntity.bankName}`);
    doc.text(`${data.settlementEntity.accountName}`);
    doc.text(`Acct: ${data.settlementEntity.accountNumber}`);
    doc.moveDown(2);
    doc.fontSize(9).fillColor('#666').text('Triple A Realty Projects Ltd. · Generated by Propa3', {
      align: 'center',
    });

    doc.end();
  });
}
