import PDFDocument from '../common/pdfkit';
import { PassThrough } from 'stream';

type SettlementBlock = {
  label: string;
  name: string;
  bankName: string;
  accountName: string;
  accountNumber: string;
  amount: number;
  pct?: number;
};

export type TenancyOfferPdfData = {
  number: string;
  applicantName: string;
  propertyLabel: string;
  rentAnnual: number;
  cautionAmount: number;
  agencyFeePct: number;
  agencyFeeAmount: number;
  legalFeePct: number;
  legalFeeAmount: number;
  managementFeePct: number;
  managementFeeAmount: number;
  serviceChargeAnnual: number;
  estateServiceCharge: number;
  serviceChargeNotes: string | null;
  settlements: SettlementBlock[];
  issuedAt: Date;
};

export function buildTenancyOfferPdf(data: TenancyOfferPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];

    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);

    doc.pipe(stream);

    doc.fontSize(18).fillColor('#1a2744').text('Offer Letter', { align: 'center' });
    doc.fontSize(10).fillColor('#666').text('Triple A Realty / A. A Laucarie Consulting', {
      align: 'center',
    });
    doc.moveDown();
    doc.fontSize(10).fillColor('#333');
    doc.text(`Offer No: ${data.number}`);
    doc.text(`Date: ${data.issuedAt.toLocaleDateString('en-NG')}`);
    doc.text(`Applicant: ${data.applicantName}`);
    doc.text(`Property: ${data.propertyLabel}`);
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('Financial summary', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#333');
    const money = (n: number) =>
      `₦${n.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;

    doc.text(`Annual rent: ${money(data.rentAnnual)}`);
    doc.text(`Caution deposit: ${money(data.cautionAmount)}`);
    doc.text(
      `Agency fee (${data.agencyFeePct}%): ${money(data.agencyFeeAmount)}`,
    );
    doc.text(`Legal fee (${data.legalFeePct}%): ${money(data.legalFeeAmount)}`);
    doc.text(
      `Management fee (${data.managementFeePct}%): ${money(data.managementFeeAmount)}`,
    );
    doc.text(`Service charge (annual): ${money(data.serviceChargeAnnual)}`);
    doc.text(`Estate service charge: ${money(data.estateServiceCharge)}`);
    if (data.serviceChargeNotes) {
      doc.moveDown(0.3);
      doc.fontSize(9).fillColor('#555').text(data.serviceChargeNotes);
    }

    doc.moveDown();
    doc.fontSize(12).fillColor('#1a2744').text('Settlement accounts (Doc 10)', {
      underline: true,
    });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#333');

    if (!data.settlements.length) {
      doc.text('Settlement entities not yet assigned — update offer payees before payment.');
    } else {
      for (const s of data.settlements) {
        doc.fillColor('#1a2744').text(s.label, { continued: false });
        doc.fillColor('#333');
        doc.text(`${s.name}`);
        doc.text(`${s.bankName} · ${s.accountName}`);
        doc.text(`Acct: ${s.accountNumber}`);
        doc.text(
          `Amount: ${money(s.amount)}${s.pct != null ? ` (${s.pct}%)` : ''}`,
        );
        doc.moveDown(0.6);
      }
    }

    doc.moveDown();
    doc
      .fontSize(9)
      .fillColor('#666')
      .text(
        'Note: Application form Agency+Legal 20% clause (Doc 12) is separate from this offer split (Agency 10% + Legal 5% + Management 5%).',
        { align: 'left' },
      );
    doc.moveDown(2);
    doc.text('Generated by Propa3', { align: 'center' });

    doc.end();
  });
}
