import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

type LogPdfData = {
  refCode: string;
  date: Date;
  projectName: string;
  projectLocation: string;
  startTime: string | null;
  endTime: string | null;
  status: string;
  siteCode: string;
  activities: { activity: string; status: string; progressPercent: number }[];
  ironBenders: number;
  carpenters: number;
  masons: number;
  materials: { material: string; receivedQty: number; consumedQty: number; balance: number }[];
  qualitySlumpTest: boolean;
  safetyPpeCompliance: boolean;
  supervisorSignature: string | null;
  nextDayActivities: string | null;
};

export function buildSiteLogPdf(data: LogPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];

    stream.on('data', (c: Buffer) => chunks.push(c));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);

    doc.pipe(stream);

    doc.fontSize(16).fillColor('#1a2744').text('Daily Site Activities Tracker', { align: 'center' });
    doc.fontSize(10).fillColor('#333').text('Triple A Realty Projects Ltd.', { align: 'center' });
    doc.moveDown();

    doc.text(`Ref: ${data.refCode}`);
    doc.text(`Site: ${data.siteCode} · Date: ${data.date.toLocaleDateString('en-NG')}`);
    doc.text(`Project: ${data.projectName}`);
    doc.text(`Location: ${data.projectLocation}`);
    doc.text(`Time: ${data.startTime ?? '—'} – ${data.endTime ?? '—'} · Status: ${data.status}`);
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('Activities');
    doc.fontSize(9).fillColor('#333');
    for (const a of data.activities) {
      doc.text(`• ${a.activity} — ${a.status} (${a.progressPercent}%)`);
    }
    doc.moveDown();

    doc.fontSize(12).fillColor('#1a2744').text('Manpower');
    doc.fontSize(9).fillColor('#333');
    doc.text(
      `Iron benders: ${data.ironBenders} · Carpenters: ${data.carpenters} · Masons: ${data.masons}`,
    );
    doc.moveDown();

    if (data.materials.length) {
      doc.fontSize(12).fillColor('#1a2744').text('Materials');
      doc.fontSize(9).fillColor('#333');
      for (const m of data.materials) {
        doc.text(
          `${m.material}: recv ${m.receivedQty} · used ${m.consumedQty} · bal ${m.balance}`,
        );
      }
      doc.moveDown();
    }

    doc.fontSize(12).fillColor('#1a2744').text('Quality & Safety');
    doc.fontSize(9).fillColor('#333');
    doc.text(`Slump test: ${data.qualitySlumpTest ? 'Yes' : 'No'}`);
    doc.text(`PPE compliance: ${data.safetyPpeCompliance ? 'Yes' : 'No'}`);
    doc.moveDown();

    if (data.nextDayActivities) {
      doc.fontSize(12).fillColor('#1a2744').text('Plan for next day');
      doc.fontSize(9).fillColor('#333').text(data.nextDayActivities);
      doc.moveDown();
    }

    if (data.supervisorSignature) {
      doc.text(`Supervisor signature: ${data.supervisorSignature}`);
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#666').text('Generated by Propa3', { align: 'center' });

    doc.end();
  });
}
